image: nixos/nix:latest

build:
  stage: build
  script:
    - nix-env -iA nixpkgs.cachix
    - cachix use icy-matrix && cachix authtoken $CACHIX_AUTH_TOKEN
    - nix-build nix/default.nix
    - nix-store --query --references $(nix-instantiate nix/default.nix) | xargs nix-store --realise | xargs nix-store --query --requisites | cachix push icy-matrix