[package]
name = "icy_matrix"
version = "0.1.0"
authors = ["Yusuf Bera Ertan <y.bera003.06@protonmail.com>"]
edition = "2018"

[profile.dev]
debug = false
panic = "abort"

[profile.release]
lto = "thin"

[dependencies]
iced = { git = "https://github.com/yusdacra/iced", branch = "icy_matrix", features = ["tokio", "image"] }
iced_native = { git = "https://github.com/yusdacra/iced", branch = "icy_matrix" }
iced_futures = { git = "https://github.com/yusdacra/iced", branch = "icy_matrix" }

open = "1.4.0"
infer = "0.3.4"
rfd = "0.0.3"
image = "0.23.12"
directories-next = "2.0.0"

http = "0.2"
parking_lot = "0.11.1"
tokio = { version = "1.0.1", features = ["rt-multi-thread", "parking_lot", "time", "fs"] }
ruma = { git = "https://github.com/ruma/ruma/", features = ["client-api"], branch = "main" }
ruma-client = { git = "https://github.com/ruma/ruma/", branch = "main" }
assign = "1.1.1"
uuid = { version = "0.8.1", features = ["v4"] }
ahash = "0.6"
indexmap = "1.6.1"

serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
chrono = "0.4.19"
log = "0.4.11"
simplelog = "0.9.0"
fuzzy-matcher = "0.3.7"
