[package]
name = "crust"
version = "0.1.0"
authors = ["Yusuf Bera Ertan <y.bera003.06@protonmail.com>"]
edition = "2018"
description = "Rust client for the Harmony protocol."
license = "GPLv3"
repository = "https://github.com/harmony-development/crust"
homepage = "https://github.com/harmony-development/crust"

[package.metadata.bundle]
name = "Crust"
identifier = "nodomain.yusdacra.crust"
short_description = "Rust client for the Harmony protocol."

[profile.dev]
opt-level = 2
overflow-checks = true
debug-assertions = true
debug = false
codegen-units = 256
lto = false
incremental = true

[profile.release]
opt-level = 3
lto = "thin"
overflow-checks = false
debug-assertions = false
debug = false
codegen-units = 1
panic = 'abort'

[dependencies]
harmony_rust_sdk = { git = "https://github.com/harmony-development/harmony_rust_sdk.git", branch = "workaround/tls-fix", features = ["client", "parking_lot"] }

iced = { git = "https://github.com/yusdacra/iced.git", rev = "e74a2a2003eab1c6e1f30ce88d9f5144f6b456a1", features = ["tokio", "image"] }
iced_native = { git = "https://github.com/yusdacra/iced.git", rev = "e74a2a2003eab1c6e1f30ce88d9f5144f6b456a1" }
iced_futures = { git = "https://github.com/yusdacra/iced.git", rev = "e74a2a2003eab1c6e1f30ce88d9f5144f6b456a1" }
iced_aw = { git = "https://github.com/yusdacra/iced_aw.git", rev = "63c71b4aa59d0b63c7f5b0e89761df15ef944a6d", default-features = false, features = [
    "icons",
    "card",
    "colors",
    "badge",
    "color_picker",
    "modal",
    "tab_bar",
    "tabs",
] }

open = "1.5.1"
infer = "0.4.0"
rfd = "0.3"
image = "0.23.14"
directories-next = "2.0.0"

async-mutex = "1.4.0"
tokio = { version = "1.5.0", features = ["rt-multi-thread", "parking_lot", "time", "fs", "macros"] }
uuid = { version = "0.8.2", features = ["v4"] }
ahash = "0.7"
indexmap = "1.6.1"

serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
chrono = "0.4.19"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-appender = "0.1"
fuzzy-matcher = "0.3.7"

[package.metadata.nix]
longDescription = """
Crust is a Harmony client written in Rust using the iced GUI library.

It aims to be lightweight with a good out-of-the-box experience.
"""
systems = ["x86_64-linux"]
app = true
build = true
runtimeLibs = [
    "vulkan-loader",
    "wayland",
    "wayland-protocols",
    "libxkbcommon",
    "xorg.libX11",
    "xorg.libXrandr",
    "xorg.libXi",
]
devshell.name = "crust-shell"

[package.metadata.nix.desktopFile]
name = "Crust"
genericName = "Harmony Client"
categories = "Network;"
